### ISSUE TITLE
Nice animation and design

### ISSUE THREAD

**Issue by renatajarmova** [fac18/week7-mepl#47]
Lovely design, colours and background in general.

But...

We really loved the animation in the form labels! Well done for that. It looks so amazing!

![Screen Shot 2019-12-13 at 11 04 04](https://user-images.githubusercontent.com/41273801/70795684-4e0e0e80-1d98-11ea-8479-6b53c441be25.png)

**Comment by nikkesan** [comment]
Thanks!  We tried to design mobile first and wanted to reduce text repetition.  But still haven't managed to squeeze it all on one screen yet! 🙈
